# Generated by Django 5.0.3 on 2024-04-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique_for_date='posted', verbose_name='Заголовок')),
                ('description', models.CharField(max_length=256, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Описание вакансии')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 1, 10, 39, 25, 426921), verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
                'db_table': 'Vacancys',
                'ordering': ['-posted'],
            },
        ),
    ]
