# Generated by Django 5.0.3 on 2024-04-01 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vacancy_id_alter_vacancy_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 1, 10, 44, 10, 919135), verbose_name='Опубликована'),
        ),
    ]
