# Generated by Django 5.0.3 on 2024-04-02 12:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_vacancy_author_alter_vacancy_posted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 2, 15, 8, 9, 292339), verbose_name='Опубликована'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отклика')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 2, 15, 8, 9, 293336), verbose_name='Дата отклика')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacancy', verbose_name='Вакансия отклика')),
            ],
            options={
                'verbose_name': 'Отклики к вакансии',
                'verbose_name_plural': 'Отклики к вакансиям',
                'db_table': 'Comment',
                'ordering': ['-date'],
            },
        ),
    ]
