# Generated by Django 5.0.3 on 2024-04-05 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_vacancy_posted_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 5, 12, 50, 0, 370105), verbose_name='Дата отклика'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 5, 12, 50, 0, 369108), verbose_name='Опубликована'),
        ),
    ]
