# Generated by Django 5.0.3 on 2024-04-05 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vacancy_image_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 5, 13, 34, 31, 305211), verbose_name='Дата отклика'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 5, 13, 34, 31, 304218), verbose_name='Опубликована'),
        ),
    ]
