# Generated by Django 5.0.3 on 2024-04-05 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comment_date_alter_vacancy_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 5, 13, 35, 6, 831528), verbose_name='Дата отклика'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 5, 13, 35, 6, 831528), verbose_name='Опубликована'),
        ),
    ]
